N5Utils.saveRegion writes into an existing dataset
saalfeldlab/n5-imglib2 pull request #19
Opened 2021-01-29 23:01 UTC by bogovicj

* add test of this method

2021-02-01 17:25 UTC, bogovicj commented
pass DatasetAttributes to saveRegion

2021-02-01 18:40 UTC, axtimwalde requested changes
ExecutorService is not used to parallelize as far as I can see.

2021-02-26 03:27 UTC, axtimwalde commented
That ready to go?

2021-02-26 03:31 UTC, axtimwalde commented on src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java
> +	public static <T extends NativeType<T>> void saveRegion(
Add Javadoc.

2021-02-26 03:31 UTC, axtimwalde commented on src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java
> +	public static <T extends NativeType<T>> void saveRegion(
Add Javadoc.

2021-03-09 16:30 UTC, bogovicj commented on src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java
> +	public static <T extends NativeType<T>> void saveRegion(
Added in 2696c84

2021-03-09 16:31 UTC, bogovicj commented
Think this is good to go now @axtimwalde

2021-03-10 16:38 UTC, merged

2021-03-10 16:38 UTC, axtimwalde commented
Thanks a lot!